name: General Tests

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.1"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Trusted Key adding for Chrome install
        run: wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | tee /etc/apt/trusted.gpg.d/google.asc >/dev/null

      - name: Adding Chrome to repository
        run: sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'

      - name: Update apt and install Chrome
        run: apt-get -y update && apt-get install -y google-chrome-stable

      - name: Install Python pandas library
        run: pip install pandas

      - name: Install Python openpyxl library
        run: pip install openpyxl

      - name: Install Python beautifulsoup4 library
        run: pip install beautifulsoup4

      - name: Install selenium library
        run: pip install selenium

      - name: Upgrade Python requests library
        run: pip install --upgrade requests

      - name: Clone BSC repository
        uses: actions/checkout@v4
        with:
          repository: t6kke/BadmintonSkillCalculator
          #ref: alpha4
          path: /home/runner/work/skill-calculator/skill-calculator/BSC

      - name: go test
        run: go test -cover ./...

      - name: build test
        run: go build
